version: "3"

services:
  axon-server:
    image: axoniq/axonserver:4.6.4
    container_name: axon-server
    healthcheck:
      test: curl -f http://localhost:8024/actuator/health || exit 1;
    ports:
      - 8024:8024
      - 8124:8124

  # postgres:
    # image: postgres:15
    # environment:
    #   POSTGRES_USER: admin
    #   POSTGRES_PASSWORD: 1234

  # docker run -d --name axon -p 8080:10080/tcp -d axonivy/axonivy-engine:11.1
  # docker run -d --name axonserver -p 8024:8024 -p 8124:8124 axoniq/axonserver